In [53]:
import pandas as pd
import numpy as np
import torch
from sklearn import metrics

In [229]:
df_all = pd.read_csv("valval_gt_all.csv")

In [230]:
df_all

case  epoch       answer
0       A2020-EM-01-0001      1         Wake
1       A2020-EM-01-0001      2         Wake
2       A2020-EM-01-0001      3         Wake
3       A2020-EM-01-0001      4         Wake
4       A2020-EM-01-0001      5         Wake
...                  ...    ...          ...
132778  A2021-EM-01-0170    838  Light Sleep
132779  A2021-EM-01-0170    839  Light Sleep
132780  A2021-EM-01-0170    840  Light Sleep
132781  A2021-EM-01-0170    841         Wake
132782  A2021-EM-01-0170    842         Wake

[132783 rows x 3 columns]

In [250]:
case_lst = list(df_all.case.value_counts().index)

In [278]:
case_lst = list(df["Video_name"].value_counts().index)

In [232]:
ref_all = list(df_all["answer"].map({"Wake": 2, "Light Sleep": 1, "Deep Sleep": 0}))

In [ ]:
df_all.answer

In [231]:
df_all.case.value_counts()

A2021-EM-01-0018    1177
A2021-EM-01-0076    1150
A2020-EM-01-0116    1073
A2020-EM-01-0066    1002
A2020-EM-01-0057     987
                    ... 
A2021-EM-01-0074     684
A2021-EM-01-0116     673
A2021-EM-01-0165     646
A2021-EM-01-0132     593
A2021-EM-01-0006     554
Name: case, Length: 160, dtype: int64

In [280]:
tmp = list(df["Video_name"].value_counts())

In [281]:
import random

In [282]:
pick = ["Light Sleep", "Deep Sleep", "Wake"]

In [6]:
pred = np.load("predicted_values_max_v008.npy", allow_pickle=True)

In [55]:
pred.shape

(32888,)

In [24]:
pred_cpu = [np.array(x.to('cpu')) for x in pred]

In [28]:
pred_arr = np.array(pred_cpu)

In [35]:
pred_arr

array([[[0.2081236 , 0.24465135, 0.2472251 ]],

       [[0.3081236 , 0.34465134, 0.3472251 ]],

       [[0.3081236 , 0.34465134, 0.3472251 ]],

       ...,

       [[0.30905685, 0.37891775, 0.31202537]],

       [[0.30905685, 0.37891775, 0.31202537]],

       [[0.30905685, 0.37891775, 0.31202537]]], dtype=float32)

In [34]:
pred_arr_t = pred_arr.reshape(32888, 3)

In [36]:
pred_arr_t

array([[0.2081236 , 0.24465135, 0.2472251 ],
       [0.3081236 , 0.34465134, 0.3472251 ],
       [0.3081236 , 0.34465134, 0.3472251 ],
       ...,
       [0.30905685, 0.37891775, 0.31202537],
       [0.30905685, 0.37891775, 0.31202537],
       [0.30905685, 0.37891775, 0.31202537]], dtype=float32)

In [57]:
pred_tem = np.zeros(((32891, 3)))

In [88]:
pred_tem[:32888] = pred_arr_t

In [89]:
pred_tem[-3:] = np.array([[0.30905685, 0.37891775, 0.31202537],
                           [0.30905685, 0.37891775, 0.31202537],
                           [0.30905685, 0.37891775, 0.31202537]])

In [90]:
pred_tem

array([[0.20812359, 0.24465135, 0.24722511],
       [0.30812359, 0.34465134, 0.3472251 ],
       [0.30812359, 0.34465134, 0.3472251 ],
       ...,
       [0.30905685, 0.37891775, 0.31202537],
       [0.30905685, 0.37891775, 0.31202537],
       [0.30905685, 0.37891775, 0.31202537]])

In [68]:
pred_class = np.argmax(pred_tem, axis=-1)

In [69]:
pred_class

array([2, 2, 2, ..., 1, 1, 1])

In [226]:
df_v = pd.read_csv("valval_gt.csv")

In [227]:
df_v

Case  Start_Epoch       answer
0    A2021-EM-01-0169          580   Deep Sleep
1    A2021-EM-01-0169          581   Deep Sleep
2    A2021-EM-01-0169          582  Light Sleep
3    A2021-EM-01-0169          583  Light Sleep
4    A2021-EM-01-0169          584  Light Sleep
..                ...          ...          ...
994  A2021-EM-01-0170          837  Light Sleep
995  A2021-EM-01-0170          838  Light Sleep
996  A2021-EM-01-0170          839  Light Sleep
997  A2021-EM-01-0170          840  Light Sleep
998  A2021-EM-01-0170          841         Wake

[999 rows x 3 columns]

In [46]:
df

Video_name  epoch       answer
0      A2020-EM-01-0005      1         Wake
1      A2020-EM-01-0005      2         Wake
2      A2020-EM-01-0005      3         Wake
3      A2020-EM-01-0005      4  Light Sleep
4      A2020-EM-01-0005      5  Light Sleep
...                 ...    ...          ...
32886  A2021-EM-01-0163    930   Deep Sleep
32887  A2021-EM-01-0163    931   Deep Sleep
32888  A2021-EM-01-0163    932   Deep Sleep
32889  A2021-EM-01-0163    933   Deep Sleep
32890  A2021-EM-01-0163    934         Wake

[32891 rows x 3 columns]

In [117]:
idx_n = list(df.Video_name.value_counts())

In [76]:
ref = list(df["answer"].map({"Wake": 2, "Light Sleep": 1, "Deep Sleep": 0}))

In [77]:
metrics.f1_score(ref, pred_class, average='macro')

0.33487324579668293

In [78]:
pred_tem

array([[0.20812359, 0.24465135, 0.24722511],
       [0.30812359, 0.34465134, 0.3472251 ],
       [0.30812359, 0.34465134, 0.3472251 ],
       ...,
       [0.30905685, 0.37891775, 0.31202537],
       [0.30905685, 0.37891775, 0.31202537],
       [0.30905685, 0.37891775, 0.31202537]])

In [103]:
from tqdm import tqdm

In [119]:
idx_n

[957,
 954,
 954,
 934,
 933,
 922,
 881,
 870,
 868,
 858,
 856,
 855,
 853,
 853,
 845,
 839,
 838,
 838,
 834,
 834,
 832,
 830,
 820,
 813,
 803,
 788,
 787,
 782,
 781,
 775,
 765,
 764,
 757,
 748,
 748,
 728,
 727,
 715,
 694,
 658]

In [122]:
t_lst = []
for idx in range(len(idx_n)):
    if idx == 0:
        t_lst.append(idx_n[idx])
    else:
        t_lst.append(idx_n[idx]+t_lst[idx-1])

In [123]:
t_lst

[957,
 1911,
 2865,
 3799,
 4732,
 5654,
 6535,
 7405,
 8273,
 9131,
 9987,
 10842,
 11695,
 12548,
 13393,
 14232,
 15070,
 15908,
 16742,
 17576,
 18408,
 19238,
 20058,
 20871,
 21674,
 22462,
 23249,
 24031,
 24812,
 25587,
 26352,
 27116,
 27873,
 28621,
 29369,
 30097,
 30824,
 31539,
 32233,
 32891]

In [203]:
def adaptive_weight(seg, i, j, k, ratio):
    th_arr = np.zeros(np.shape(seg))

    deepw = 1 + ratio*i
    lightw = 1 + ratio*j
    wakew = 1 + ratio*k

    th_arr[:, 0] = seg[:, 0]*deepw
    th_arr[:, 1] = seg[:, 1]*lightw
    th_arr[:, 2] = seg[:, 2]*wakew
    
    return th_arr

In [224]:
best_score = 0
a = 20

for i in range(a):
    for k in range(a):
        for j in range(a):
            final_lst = []
            for t in range(len(t_lst)):
                if t == 0:
                    segment = th_arr[:t_lst[t]]
                else:
                    segment = th_arr[t_lst[t-1]:t_lst[t]]

                seg1 = segment[:len(segment)//10]
                seg2 = segment[len(segment)//10:-len(segment)//10]
                seg3 = segment[-len(segment)//10:]

                th1 = adaptive_weight(seg1, 10, 6, 15, 1)
                th2 = adaptive_weight(seg2, 8, 13, 15, 1)
                th3 = adaptive_weight(seg3, 18, 8, 9, 1)

                cls1 = list(np.argmax(th1, axis=-1))
                cls2 = list(np.argmax(th2, axis=-1))
                cls3 = list(np.argmax(th3, axis=-1))


                final_lst.append(list(cls1))
                final_lst.append(list(cls2))
                final_lst.append(list(cls3))

            flat_list = []
            for sublist in final_lst:
                for item in sublist:
                    flat_list.append(item)

            score = metrics.f1_score(ref, flat_list, average='macro')
            if score > best_score:
                best_score = score.copy()
                print("update! at ", i, j, k)
                best_set = {"deepw": i, "lightw": j, "wakew": k}

update! at  0 0 0
update! at  0 0 1
update! at  0 0 2
update! at  0 3 8
update! at  0 8 19
update! at  1 0 0
update! at  3 1 0
update! at  5 2 1
update! at  6 2 0
update! at  6 2 1
update! at  9 4 15
update! at  14 6 0
update! at  14 6 3
update! at  16 7 0
update! at  16 7 4
update! at  16 7 8
update! at  18 8 9


In [235]:
df_csv = df.copy()

In [239]:
ans_th = list(df_csv["answer"].map({2: "Wake", 1: "Light Sleep", 0: "Deep Sleep"}))

In [241]:
df_csv.answer = ans_th

In [244]:
df_csv.to_csv("008_th.csv", index=False)

In [245]:
df_csv

Video_name  epoch       answer
0      A2020-EM-01-0005      1         Wake
1      A2020-EM-01-0005      2         Wake
2      A2020-EM-01-0005      3         Wake
3      A2020-EM-01-0005      4         Wake
4      A2020-EM-01-0005      5         Wake
...                 ...    ...          ...
32886  A2021-EM-01-0163    930  Light Sleep
32887  A2021-EM-01-0163    931  Light Sleep
32888  A2021-EM-01-0163    932  Light Sleep
32889  A2021-EM-01-0163    933  Light Sleep
32890  A2021-EM-01-0163    934  Light Sleep

[32891 rows x 3 columns]

In [225]:
best_score

0.3651069313035911

In [199]:
best_score

0.34742682382808177

In [181]:
flat_list = []
for sublist in final_lst:
    for item in sublist:
        flat_list.append(item)

In [182]:
len(flat_list)

32891

In [140]:
len(final_lst)

120

In [112]:
best_score = 0
for i in tqdm(range(5)):
    for j in range(50):
        for k in range(5):
            th_arr = np.zeros(((32891, 3)))

            deepw = 1 + 0.01*i
            lightw = 1 + 0.002*j
            wakew = 1 + 0.01*k

            th_arr[:, 0] = pred_tem[:, 0]*deepw
            th_arr[:, 1] = pred_tem[:, 1]*lightw
            th_arr[:, 2] = pred_tem[:, 2]*wakew

            th_class = np.argmax(th_arr, axis=-1)

            score = metrics.f1_score(ref, th_class, average='macro')
            if score > best_score:
                best_score = score.copy()
                print("update! at ", i, j, k)
                best_set = {"deepw": i, "lightw": j, "wakew": k}

  0%|          | 0/5 [00:00<?, ?it/s]

update! at  0 0 0
update! at  0 1 0
update! at  0 2 0
update! at  0 3 0
update! at  0 4 0
update! at  0 5 0
update! at  0 6 1
update! at  0 7 1
update! at  0 26 0
update! at  0 26 1
update! at  0 27 0
update! at  0 27 1
update! at  0 28 1
update! at  0 29 0
update! at  0 30 0
update! at  0 33 0
update! at  0 34 0
update! at  0 34 1
update! at  0 36 0
update! at  0 36 1
update! at  0 37 0
update! at  0 37 1
update! at  0 38 0
update! at  0 39 0


100%|██████████| 5/5 [00:25<00:00,  5.11s/it]


In [113]:
best_score

0.34562018267141165

In [111]:
best_score

0.34561688415277714